web:
  image: php
  command: php -S 0.0.0.0:8000 -t /app
  links:
    - db
  ports:
    - "8000:8000"
  volumes:
    - ./app:/app
db:
  image: mysql
  volumes:
    - ./schema:/schema
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: demo