web:
  build: .
  links:
    - db
  ports:
    - "8000:80"
  volumes:
    - ./app:/var/www/html
db:
  image: mysql
  volumes:
    - ./schema:/schema
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: demo